name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest-large, macos-latest]
        include:
          - os: macos-latest-large
            arch: amd64
          - os: macos-latest
            arch: arm64

    steps:
    - uses: actions/checkout@v4
    - name: build object file
      run: cc busy_loop.c -c -o busy_loop_${{ matrix.arch }}.o
    - name: objdump object file
      run: objdump -d busy_loop_${{ matrix.arch }}.o
    - name: build executable
      run: cc busy_loop.c -nostartfiles -o busy_loop_${{ matrix.arch }}
    - name: objdump executable
      run: objdump -d busy_loop_${{ matrix.arch }}
